import Head from "next/head";
import Header from "@/components/Header";
import { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import { FileSystemTree } from "@webcontainer/api";
import { useEffect } from "react";
import { useAppDispatch } from "@/hooks/useAppDispatch";
import DockView from "@/components/dockview/DockView";
import { setFileSystemTree } from "@/features/fileTree/fileTreeSlice";
import {
  initializeTerminal,
  installDependencies,
  selectInitializingEsbuild,
  selectWebcontainerStarted,
} from "@/features/webcontainer/webcontainerSlice";
import { useAppSelector } from "@/hooks/useAppSelector";
import JSZip from "jszip";

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { projectId } = query;
  try {
    const responseProject = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/project/${projectId}`
    );
    const response = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/fileTree/${projectId}`
    );
    const { data } = response;
    return {
      props: { ...responseProject.data, ...data },
    };
  } catch {
    return {
      props: { data: null },
    };
  }
};

const Home: NextPage<HomeProps> = ({ fileSystemTree, name, _id }) => {
  const dispatch = useAppDispatch();
  const webcontainerStarted = useAppSelector(selectWebcontainerStarted);
  const initializingWebcontainer = useAppSelector(selectInitializingEsbuild);
  const hasPackageJSON = "package*json" in fileSystemTree;
  const installDirectories =
    "contracts" in fileSystemTree && "ui" in fileSystemTree
      ? [
          { directory: "contracts", build: true },
          { directory: "ui", build: false },
        ]
      : [];

  useEffect(() => {
    if (!webcontainerStarted) {
      dispatch(installDependencies({ fileSystemTree, hasPackageJSON }));
      return;
    }
  }, [webcontainerStarted]);

  useEffect(() => {
    if (initializingWebcontainer) return;
    dispatch(initializeTerminal({ installDirectories }));
  }, [initializingWebcontainer]);

  useEffect(() => {
    dispatch(setFileSystemTree(fileSystemTree));
  }, []);

  const onDownload = async () => {
    const zip = new JSZip();

    const src = {
      src: {
        // Because it's a directory, add the "directory" key
        directory: {
          // This is a file - provide its path as a key:
          "main.js": {
            // Because it's a file, add the "file" key
            file: {
              contents: `
            console.log('Hello from WebContainers!')
          `,
            },
          },
          // This is another file inside the same folder
          "main.css": {
            // Because it's a file, add the "file" key
            file: {
              contents: `
            body {
              margin: 0;
            }
          `,
            },
          },
        },
      },
      "package.json": {
        file: {
          contents: `
        {
          "name": "vite-starter",
          "private": true,
          "version": "0.0.0",
          "type": "module",
          "scripts": {
            "dev": "vite",
            "build": "vite build",
            "preview": "vite preview"
          },
          "devDependencies": {
            "vite": "^4.0.4"
          }
        }`,
        },
      },
    };

    function processObject(obj) {
      for (const key in obj) {
        console.log(obj[key]);
      }
    }

    processObject(src);

    zip.generateAsync({ type: "base64" }).then(function (base64) {
      window.location = "data:application/zip;base64," + base64;
      // saveAs(content, "example.zip");
    });
  };

  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <button onClick={onDownload}>download</button>
        <DockView id={_id} name={name} />
      </main>
    </>
  );
};

interface HomeProps {
  fileSystemTree: FileSystemTree;
  _id: string;
  name: string;
  type: number;
  visibility: boolean;
  files_id: number;
}

export default Home;
