import Head from "next/head";
import Header from "@/components/Header";
import { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import { FileSystemTree } from "@webcontainer/api";
import { useEffect } from "react";
import { useAppDispatch } from "@/hooks/useAppDispatch";
import DockView from "@/components/dockview/DockView";
import { setFileSystemTree } from "@/features/fileTree/fileTreeSlice";
import {
  initializeTerminal,
  installDependencies,
  selectInitializingEsbuild,
  selectWebcontainerStarted,
} from "@/features/webcontainer/webcontainerSlice";
import { useAppSelector } from "@/hooks/useAppSelector";
export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { projectId } = query;
  try {
    const responseProject = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/project/${projectId}`
    );
    const response = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/fileTree/${projectId}`
    );
    const { data } = response;
    return {
      props: { ...responseProject.data, ...data },
    };
  } catch {
    return {
      props: { data: null },
    };
  }
};

const Home: NextPage<HomeProps> = ({ fileSystemTree, name, _id }) => {
  const dispatch = useAppDispatch();
  const webcontainerStarted = useAppSelector(selectWebcontainerStarted);
  const initializingWebcontainer = useAppSelector(selectInitializingEsbuild);
  const hasPackageJSON = "package*json" in fileSystemTree;
  const installDirectories =
    "contracts" in fileSystemTree && "ui" in fileSystemTree
      ? [
          { directory: "contracts", build: true },
          { directory: "ui", build: false },
        ]
      : [];

  useEffect(() => {
    if (!webcontainerStarted) {
      dispatch(installDependencies({ fileSystemTree, hasPackageJSON }));
      return;
    }
  }, [webcontainerStarted]);

  useEffect(() => {
    if (initializingWebcontainer) return;
    dispatch(initializeTerminal({ installDirectories }));
  }, [initializingWebcontainer]);

  useEffect(() => {
    dispatch(setFileSystemTree(fileSystemTree));
  }, []);

  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <DockView id={_id} name={name} />
      </main>
    </>
  );
};

interface HomeProps {
  fileSystemTree: FileSystemTree;
  _id: string;
  name: string;
  type: number;
  visibility: boolean;
  files_id: number;
}

export default Home;
