import Head from "next/head";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import ReadMoreSection from "@/components/ReadMoreSection";
import Footer from "@/components/Footer";

const Home = () => {
  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <HeroSection />
        <ReadMoreSection />
        <Footer />
      </div>
    </>
  );
};

export default Home;
