import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Editor from "@monaco-editor/react";
import { files } from "../../files";
import { useCallback, useState } from "react";
import {
  getWorker,
  MonacoJsxSyntaxHighlight,
} from "monaco-jsx-syntax-highlight";

const Home = () => {
  const [code, setCode] = useState<string | undefined>(
    files.pages.directory["_app.page.tsx"].file.contents
  );

  const handleEditorDidMount = useCallback((editor: any, monaco: any) => {
    monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
      jsx: monaco.languages.typescript.JsxEmit.Preserve,
      target: monaco.languages.typescript.ScriptTarget.ES2020,
      esModuleInterop: true,
    });

    monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions({
      noSemanticValidation: true,
      noSyntaxValidation: true,
    });

    const monacoJsxSyntaxHighlight = new MonacoJsxSyntaxHighlight(
      getWorker(),
      monaco
    );

    const { highlighter, dispose } =
      monacoJsxSyntaxHighlight.highlighterBuilder({
        editor: editor,
      });

    highlighter();

    editor.onDidChangeModelContent(() => {
      highlighter();
    });

    return dispose;
  }, []);

  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className="flex flex-1">
          <div className="flex flex-1 flex-col">
            <div className="flex-1 border-b-2">
              <Editor
                className="editor"
                path={"file:///index.tsx"}
                defaultLanguage="typescript"
                defaultValue={code}
                onChange={setCode}
                onMount={handleEditorDidMount}
                options={{
                  fontSize: 16,
                  lineHeight: 28,
                  automaticLayout: true,
                }}
              />
            </div>
            <div className="flex-1"></div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
