import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Login from "@/components/Login";

const Home = () => {
  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Login />
        <Footer />
      </main>
    </>
  );
};

export default Home;
