import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import { NextPage } from "next";
import axios from "axios";
import { FormEvent, useState } from "react";
import { useRouter } from "next/router";

const Project: NextPage = () => {
  const [name, setName] = useState("");
  const router = useRouter();

  const createProject = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}/project`,
        { name, type: 0, visibility: true, files_id: 1 },
        { headers: { "Content-Type": "application/json" } }
      );
      router.push(`/project/${response.data.project_id}`);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <section className="bg-gray-50">
          <div className="flex justify-center m-4 sm:m-8">
            <div className="w-full lg:max-w-xl p-6 space-y-8 sm:p-8 bg-white rounded-lg shadow-xl">
              <h2 className="text-2xl font-bold text-gray-900">
                Create a new project
              </h2>
              <form onSubmit={createProject} className="mt-8 space-y-6">
                <div>
                  <label
                    htmlFor="name"
                    className="block mb-2 text-sm font-medium text-gray-900"
                  >
                    Project name
                  </label>
                  <input
                    type="text"
                    name="name"
                    id="name"
                    value={name}
                    onChange={(evt) => setName(evt.target.value)}
                    className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                    placeholder="My project"
                    required
                  />
                </div>
                <button
                  type="submit"
                  className="w-full px-5 py-3 text-base font-medium text-center text-white bg-gray-700 rounded-lg hover:bg-black focus:ring-4 focus:ring-blue-300 sm:w-auto"
                >
                  Create project
                </button>
              </form>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Project;
