import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Tree from "@/components/file-explorer/Tree";
import type { FileSystemTree } from "@webcontainer/api";

const data: FileSystemTree = {
  src: {
    directory: {
      "main.js": {
        file: {
          contents: `
            console.log('Hello')
          `,
        },
      },
    },
  },
  test: {
    directory: {
      "main2.js": {
        file: {
          contents: `
            console.log('Hello')
          `,
        },
      },
    },
  },
  testok: {
    directory: {
      testok2: {
        directory: {
          "main2.js": {
            file: {
              contents: `
            console.log('Hello')
          `,
            },
          },
        },
      },
    },
  },
};

const Home = () => {
  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={"m-4"}>
          <Tree data={data} />
        </div>
      </main>
    </>
  );
};

export default Home;
