import Head from "next/head";
import Header from "@/components/Header";
import { GetServerSideProps, NextPage } from "next";
import axios from "axios";
import { FileSystemTree } from "@webcontainer/api";
import dayjs from "dayjs";
import { useRouter } from "next/router";

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const { projectId } = query;

  try {
    const response = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/versionControl/${projectId}`
    );
    const { data } = response;
    return {
      props: { data },
    };
  } catch {
    return {
      props: { data: null },
    };
  }
};

const Home: NextPage<HomeProps> = ({ data }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Mina Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <h1 className="text-xl text-gray-200 p-2">Your commits:</h1>
        <div className="overflow-x-auto cursor-pointer text-gray-200">
          <table className="table">
            <tbody>
              {data.map(({ files, message, _id, createdAt }) => (
                <tr
                  className="hover"
                  onClick={() => router.push(`/commit/${_id}`)}
                >
                  <td>{_id}</td>
                  <td>{message}</td>
                  <td>{dayjs(createdAt).format("DD-MM-YYYY HH:mm")}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

interface HomeProps {
  fileSystemTree: FileSystemTree;
  _id: string;
  name: string;
  type: number;
  visibility: boolean;
  files_id: number;
}

export default Home;
